/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kwon37xi' at '16. 12. 24 오후 9:30' with Gradle 3.2.1
 *
 * @author kwon37xi, @date 16. 12. 24 오후 9:30
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
